import React from 'react'
import Head from "next/head";
import Image from "next/image";
import styles from '../../styles/Home.module.css'
import TaskView from '../../src/components/elements/task/TaskView';

// Task page 

export default function testTask() {
  return (
    <div className={styles.container}>
         <Head>
        <title>Task: test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>TaskNote</h1>
        <TaskView />
        </main>
    </div>
  )
}
