import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../../../../styles/Home.module.css";
import Task from "../task/TaskCard";
import NavBar from "../nav/NavBar";
import SimpleModal from "../../elements/modal/Modal";

// Mock datasource:

import mockData from "../../../../public/data/mockData";

export default function TaskList() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TaskList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <main className={styles.main}>
        {/* Add a new task */}
        <SimpleModal />
        {mockData.map((task) => (
          <Task data={task} />
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image
              src="/logo.png"
              alt="TaskNote Logo"
              width={200}
              height={100}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
